In [ ]:
from ast import If

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# verifica na pasta atual cwd()
BASE_DIR = Path().cwd()

FILE_PATH = BASE_DIR / "Preços semestrais - AUTOMOTIVOS_2026.01.csv"

print(BASE_DIR)
print(FILE_PATH.exists())

df_precos_1_semestre = pd.read_csv(FILE_PATH, sep=";", encoding="UTF-8", low_memory=True)

df_preco_gasolina = df_precos_1_semestre["Produto"] == "GASOLINA"
# pegando o mes 6 de 2026 do estado de estado escolhido, o day_first é para datas que o dia começa primeiro
df_data = pd.to_datetime(df_precos_1_semestre["Data da Coleta"], dayfirst=True) 
# criando um filtro para o estado sp, o produto gasolina e o mes 6 de 2026
df_dia30_mes6_ano2026 = (
df_pegando_estados = sorted(df_precos_1_semestre["Estado - Sigla"].dropna().unique()))

df_estado = (df_precos_1_semestre["Estado - Sigla"] == estado_escolhido)
print("Estados Disponíveis: ")
for i in range(0, len(df_pegando_estados), 5):
    print(df_pegando_estados[i:i + 5])

estado_escolhido = input("Escolha um estado: ").strip().upper()
    (df_data.dt.day == 30) &
    (df_data.dt.month == 6) & 
    (df_data.dt.year == 2026))
filtro_estado_gasolina_mes6_ano2026 = df_preco_gasolina & df_estado & df_dia30_mes6_ano2026
# aplicando o filtro 
df_precos_1_semestre = df_precos_1_semestre[filtro_estado_gasolina_mes6_ano2026]

if df_precos_1_semestre.empty:
    print("Nenhum dado encontrado.")
    
    # exibindo o precos
else:
    df_precos_1_semestre["Valor de Venda"] = (df_precos_1_semestre["Valor de Venda"].str.replace(",", ".")).astype(float)
    # Pegando o estado sigla 


    df_filtrado = df_precos_1_semestre.copy(deep=True)
    df_resultado_total = (
        df_filtrado.groupby(["Estado - Sigla", "Municipio"], as_index=False).agg(
            media_preco=("Valor de Venda", "mean"),
            maior_preco=("Valor de Venda", "max"),
            menor_preco=("Valor de Venda", "min")
        )
    )
# resumo_total = df_resultado_total.agg(
#     maior_media=("media_preco", "max"),
#     maior_preco=("maior_preco", "max"),
#     menor_preco=("menor_preco", "min")
# )
# display(resumo_total)

# df_resumo = pd.DataFrame([
#     df_resultado_total.loc[
#         df_resultado_total["media_preco"].idxmax()
#     ],
#     df_resultado_total.loc[
#         df_resultado_total["maior_preco"].idxmax()
#     ],
#     df_resultado_total.loc[
#         df_resultado_total["menor_preco"].idxmin()
#     ]
# ])

# display(df_resumo)

# df_resultado_total["categoria_media"] = pd.qcut(
#     df_resultado_total["media_preco"],
#     q=3,
#     labels=["MENOR", "MEDIANO", "MAIOR"]
# )
# df_resultado_total["categoria_maior"] = pd.qcut(
#     df_resultado_total["maior_preco"],
#     q=3,
#     labels=["MENOR", "MEDIANO", "MAIOR"]
# )
# df_resultado_total["categoria_menor"] = pd.qcut(
#     df_resultado_total["menor_preco"],
#     q=3,
#     labels=["MENOR", "MEDIANO", "MAIOR"]
# )

# df_maiores_precos = df_resultado_total[df_resultado_total["categoria_media"] == "MAIOR"]
# df_media_precos = df_resultado_total[df_resultado_total["categoria_media"] == "MEDIANO"]
# df_menores_precos = df_resultado_total[df_resultado_total["categoria_maior"] == "MENOR"]

# display(df_maiores_precos, df_media_precos, df_menores_precos)

df_maiores_precos = df_resultado_total.sort_values(by=["maior_preco"], ascending=False)
df_maiores_precos = df_maiores_precos.reset_index(drop=True)
#######################################################################
df_media_precos = df_resultado_total.sort_values(by=["media_preco"], ascending=False)
df_media_precos = df_media_precos.reset_index(drop=True)
#######################################################################
df_menores_precos = df_resultado_total.sort_values(by=["menor_preco"], ascending=True)
df_menores_precos = df_menores_precos.reset_index(drop=True)
df_maior_preco = ["Estado - Sigla","Municipio","maior_preco"]
df_media_preco = ["Estado - Sigla","Municipio","media_preco"]
df_menor_preco = ["Estado - Sigla","Municipio","menor_preco"]
# display(df_maiores_precos[df_maior_preco])
# display(df_media_precos[df_media_preco])
# display(df_menores_precos[df_menor_preco])

df_primeiro_maior_preco = df_maiores_precos.head(1)
df_primeiro_media_preco = df_media_precos.head(1)
df_primeiro_menor_preco = df_menores_precos.head(1)

display(df_primeiro_maior_preco)
display(df_primeiro_media_preco)
display(df_primeiro_menor_preco)

In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# verifica na pasta atual cwd()
BASE_DIR = Path().cwd()

FILE_PATH = BASE_DIR / "Preços semestrais - AUTOMOTIVOS_2026.01.csv"

print(BASE_DIR)
print(FILE_PATH.exists())

df_precos_1_semestre = pd.read_csv(FILE_PATH, sep=";", encoding="UTF-8", low_memory=True)

if df_precos_1_semestre.empty:
    print("Nenhum dado encontrado.")



    filtro_estado_gasolina_mes6_ano2026 = df_preco_gasolina & df_estado & df_dia30_mes6_ano2026
    # aplicando o filtro 
    df_precos_1_semestre = df_precos_1_semestre[filtro_estado_gasolina_mes6_ano2026]


else:
    df_pegando_estados = sorted(df_precos_1_semestre["Estado - Sigla"].dropna().unique())
    print("Estados Disponíveis: ")
    for i in range(0, len(df_pegando_estados), 5):
        print(df_pegando_estados[i:i + 5])

    estado_escolhido = input("Escolha um estado: ").strip().upper()

    df_estado = (df_precos_1_semestre["Estado - Sigla"] == estado_escolhido)
    # pegando o produto gasolina
    
    # exibindo o precos
    df_precos_1_semestre["Valor de Venda"] = (df_precos_1_semestre["Valor de Venda"].str.replace(",", ".")).astype(float)
    # Pegando o estado sigla 


    df_filtrado = df_precos_1_semestre.copy(deep=True)
    df_resultado_total = (
        df_filtrado.groupby(["Estado - Sigla", "Municipio", "Produto"], as_index=False).agg(
            media_preco=("Valor de Venda", "mean"),
            maior_preco=("Valor de Venda", "max"),
            menor_preco=("Valor de Venda", "min")
        )
    )
# resumo_total = df_resultado_total.agg(
#     maior_media=("media_preco", "max"),
#     maior_preco=("maior_preco", "max"),
#     menor_preco=("menor_preco", "min")
# )
# display(resumo_total)

# df_resumo = pd.DataFrame([
#     df_resultado_total.loc[
#         df_resultado_total["media_preco"].idxmax()
#     ],
#     df_resultado_total.loc[
#         df_resultado_total["maior_preco"].idxmax()
#     ],
#     df_resultado_total.loc[
#         df_resultado_total["menor_preco"].idxmin()
#     ]
# ])

# display(df_resumo)

# df_resultado_total["categoria_media"] = pd.qcut(
#     df_resultado_total["media_preco"],
#     q=3,
#     labels=["MENOR", "MEDIANO", "MAIOR"]
# )
# df_resultado_total["categoria_maior"] = pd.qcut(
#     df_resultado_total["maior_preco"],
#     q=3,
#     labels=["MENOR", "MEDIANO", "MAIOR"]
# )
# df_resultado_total["categoria_menor"] = pd.qcut(
#     df_resultado_total["menor_preco"],
#     q=3,
#     labels=["MENOR", "MEDIANO", "MAIOR"]
# )

# df_maiores_precos = df_resultado_total[df_resultado_total["categoria_media"] == "MAIOR"]
# df_media_precos = df_resultado_total[df_resultado_total["categoria_media"] == "MEDIANO"]
# df_menores_precos = df_resultado_total[df_resultado_total["categoria_maior"] == "MENOR"]

# display(df_maiores_precos, df_media_precos, df_menores_precos)

df_maiores_precos = df_resultado_total.sort_values(by=["maior_preco"], ascending=False)
df_maiores_precos = df_maiores_precos.reset_index(drop=True)
#######################################################################
df_media_precos = df_resultado_total.sort_values(by=["media_preco"], ascending=False)
df_media_precos = df_media_precos.reset_index(drop=True)
#######################################################################
df_menores_precos = df_resultado_total.sort_values(by=["menor_preco"], ascending=True)
df_menores_precos = df_menores_precos.reset_index(drop=True)
df_maior_preco = ["Estado - Sigla","Municipio","maior_preco"]
df_media_preco = ["Estado - Sigla","Municipio","media_preco"]
df_menor_preco = ["Estado - Sigla","Municipio","menor_preco"]
# display(df_maiores_precos[df_maior_preco])
# display(df_media_precos[df_media_preco])
# display(df_menores_precos[df_menor_preco])

df_primeiro_maior_preco = df_maiores_precos.head(1)
df_primeiro_media_preco = df_media_precos.head(1)
df_primeiro_menor_preco = df_menores_precos.head(1)

display(df_primeiro_maior_preco)
display(df_primeiro_media_preco)
display(df_primeiro_menor_preco)

c:\Users\Vitor\Desktop\Pandas\main\archives\archives_2
True
Estados Disponíveis:
['AC', 'AL', 'AM', 'AP', 'BA']
['CE', 'DF', 'ES', 'GO', 'MA']
['MG', 'MS', 'MT', 'PA', 'PB']
['PE', 'PI', 'PR', 'RJ', 'RN']
['RO', 'RR', 'RS', 'SC', 'SE']
['SP', 'TO']

  Estado - Sigla Municipio     Produto  media_preco  maior_preco  menor_preco
0             SP  OURINHOS  DIESEL S10     7.239098         9.99         5.69

,Estado - Sigla,Municipio,Produto,media_preco,maior_preco,menor_preco
0,AM,PARINTINS,GASOLINA ADITIVADA,8.75358,9.29,8.29

  Estado - Sigla Municipio Produto  media_preco  maior_preco  menor_preco
0             SP   MARILIA  ETANOL     4.134311         5.29         2.89

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# =========================
# CAMINHO DO ARQUIVO
# =========================

BASE_DIR = Path().cwd()

FILE_PATH = BASE_DIR / "Preços semestrais - AUTOMOTIVOS_2026.01.csv"

print(BASE_DIR)
print(FILE_PATH.exists())


# =========================
# LENDO O CSV
# =========================

df_precos_1_semestre = pd.read_csv(
    FILE_PATH,
    sep=";",
    encoding="UTF-8",
    low_memory=True
)


# =========================
# PEGANDO OS ESTADOS
# =========================

df_pegando_estados = sorted(
    df_precos_1_semestre["Estado - Sigla"]
    .dropna()
    .unique()
)

print("\nEstados Disponíveis:")

# Mostra 5 estados por linha
for i in range(0, len(df_pegando_estados), 5):
    print(", ".join(df_pegando_estados[i:i + 5]))


# =========================
# INPUT DO ESTADO
# =========================

estado_escolhido = input(
    "\nEscolha um estado: "
).strip().upper()


# Verifica se o estado existe
if estado_escolhido not in df_pegando_estados:

    print("\nEstado inválido.")

else:

    # =========================
    # FILTRO DO ESTADO
    # =========================

    df_estado = (
        df_precos_1_semestre["Estado - Sigla"]
        == estado_escolhido
    )


    # =========================
    # FILTRO DA GASOLINA
    # =========================

    lista_de_combustiveis = ['GASOLINA', 'DIESEL', 'DIESEL S10', 'GASOLINA ADITIVADA', 'ETANOL', 'GNV']
    # =========================
    # FILTRO DA etanol
    # =========================
    df_combustiveis = (
        df_precos_1_semestre["Produto"].isin(lista_de_combustiveis)
    )
    # =========================
    # TRANSFORMANDO A DATA
    # =========================

    df_data = pd.to_datetime(
        df_precos_1_semestre["Data da Coleta"],
        dayfirst=True
    )


    # =========================
    # FILTRO DA DATA
    # 30/06/2026
    # =========================

    df_dia30_mes6_ano2026 = (

        (df_data.dt.day == 30)
        &
        (df_data.dt.month == 6)
        &
        (df_data.dt.year == 2026)

    )


    # =========================
    # JUNTANDO TODOS OS FILTROS
    # =========================

    filtro = (
        df_estado
        &
        df_combustiveis
        &
        df_dia30_mes6_ano2026

    )


    # =========================
    # APLICANDO O FILTRO
    # =========================

    df_filtrado = df_precos_1_semestre[
        filtro
    ].copy()


    # =========================
    # VERIFICANDO SE EXISTEM DADOS
    # =========================

    if df_filtrado.empty:

        print(
            "\nNenhum dado encontrado para:"
        )

        print(f"Estado: {estado_escolhido}")
        print("Produto: GASOLINA")
        print("Data: 30/06/2026")


    else:

        # =========================
        # TRANSFORMANDO O PREÇO
        # =========================

        df_filtrado["Valor de Venda"] = (
            df_filtrado["Valor de Venda"]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .astype(float)
        )


        # =========================
        # GROUPBY
        # =========================

        df_resultado_total = (

            df_filtrado
            .groupby(
                ["Estado - Sigla", "Municipio", "Produto"],
                as_index=False
            )
            .agg(

                media_preco=(
                    "Valor de Venda",
                    "mean"
                ),

                maior_preco=(
                    "Valor de Venda",
                    "max"
                ),

                menor_preco=(
                    "Valor de Venda",
                    "min"
                )

            )

        )


        # =========================
        # MAIOR PREÇO
        # =========================

        df_maiores_precos = (

            df_resultado_total
            .sort_values(
                by="maior_preco",
                ascending=False
            )
            .reset_index(drop=True)

        )


        # =========================
        # MAIOR MÉDIA
        # =========================

        df_media_precos = (

            df_resultado_total
            .sort_values(
                by="media_preco",
                ascending=False
            )
            .reset_index(drop=True)

        )


        # =========================
        # MENOR PREÇO
        # =========================

        df_menores_precos = (

            df_resultado_total
            .sort_values(
                by="menor_preco",
                ascending=True
            )
            .reset_index(drop=True)

        )


        # =========================
        # PEGANDO O PRIMEIRO DE CADA COMBUSTÍVEL
        # =========================

        df_primeiro_maiores_preco = (
            df_resultado_total.sort_values(by="maior_preco", ascending=False).groupby("Produto", as_index=False).head(1))

        
        df_primeiro_media_preco = (
            df_resultado_total.sort_values(by="media_preco", ascending=False).groupby("Produto", as_index=False).head(1))

        
        df_primeiro_menores_preco = (
            df_resultado_total.sort_values(by="menor_preco", ascending=True).groupby("Produto", as_index=False).head(1))



        # =========================
        # EXIBINDO RESULTADOS
        # =========================

        print("\n--- MAIOR PREÇO ---")


        df_primeiro_maiores_preco[
                [
                    "Estado - Sigla",
                    "Municipio",
                    "Produto",
                    "maior_preco"
                ]
            ]

        df_primeiro_maiores_preco = df_primeiro_maiores_preco.reset_index(drop=True)
        
        display(df_primeiro_media_preco)


        print("\n--- MAIOR MÉDIA DE PREÇO ---")

        df_primeiro_media_preco[
                [
                    "Estado - Sigla",
                    "Municipio",
                    "Produto",
                    "media_preco"
                ]
            ]
        df_primeiro_media_preco = df_primeiro_media_preco.reset_index(drop=True)

        display(df_primeiro_media_preco)

        print("\n--- MENOR PREÇO ---")
        df_primeiro_menores_preco[
                [
                    "Estado - Sigla",
                    "Municipio",
                    "Produto",
                    "menor_preco"
                ]
            ]

        df_primeiro_menores_preco = df_primeiro_menores_preco.reset_index(drop=True)

        display(df_primeiro_menores_preco)

c:\Users\Vitor\Desktop\Pandas\main\archives\archives_2
True

Estados Disponíveis:
AC, AL, AM, AP, BA
CE, DF, ES, GO, MA
MG, MS, MT, PA, PB
PE, PI, PR, RJ, RN
RO, RR, RS, SC, SE
SP, TO

--- MAIOR PREÇO ---

,Estado - Sigla,Municipio,Produto,media_preco,maior_preco,menor_preco
15,SE,NOSSA SENHORA DO SOCORRO,GASOLINA ADITIVADA,7.275,7.29,7.26
12,SE,NOSSA SENHORA DO SOCORRO,DIESEL S10,7.235,7.29,7.18
11,SE,NOSSA SENHORA DO SOCORRO,DIESEL,7.185,7.19,7.18
14,SE,NOSSA SENHORA DO SOCORRO,GASOLINA,7.160,7.19,7.12
8,SE,ITABAIANA,ETANOL,5.700,5.70,5.70
5,SE,ARACAJU,GNV,4.830,4.83,4.83

--- MAIOR MÉDIA DE PREÇO ---

,Estado - Sigla,Municipio,Produto,media_preco,maior_preco,menor_preco
0,SE,NOSSA SENHORA DO SOCORRO,GASOLINA ADITIVADA,7.275,7.29,7.26
1,SE,NOSSA SENHORA DO SOCORRO,DIESEL S10,7.235,7.29,7.18
2,SE,NOSSA SENHORA DO SOCORRO,DIESEL,7.185,7.19,7.18
3,SE,NOSSA SENHORA DO SOCORRO,GASOLINA,7.160,7.19,7.12
4,SE,ITABAIANA,ETANOL,5.700,5.70,5.70
5,SE,ARACAJU,GNV,4.830,4.83,4.83

--- MENOR PREÇO ---

,Estado - Sigla,Municipio,Produto,media_preco,maior_preco,menor_preco
0,SE,ARACAJU,GNV,4.830000,4.83,4.83
1,SE,ARACAJU,ETANOL,5.531667,5.69,5.50
2,SE,ITABAIANA,DIESEL,6.948333,7.79,6.78
3,SE,ARACAJU,DIESEL S10,7.010000,7.29,6.87
4,SE,ITABAIANA,GASOLINA ADITIVADA,7.083333,7.25,7.05
5,SE,ITABAIANA,GASOLINA,7.050000,7.05,7.05

,Estado - Sigla,Municipio,Produto,media_preco,maior_preco,menor_preco
0,SE,NOSSA SENHORA DO SOCORRO,GASOLINA ADITIVADA,7.275,7.29,7.26

In [ ]:
# aplicando o filtro
df_precos_1_semestre = df_precos_1_semestre[
    filtro_estado_gasolina_mes6_ano2026
]

# verifica se o FILTRO encontrou dados
if df_precos_1_semestre.empty:

    print(
        f"Nenhum dado encontrado para o estado {estado_escolhido}, "
        "GASOLINA, dia 30/06/2026."
    )

else:

    print("Dados encontrados!")
    print("Quantidade de linhas:", len(df_precos_1_semestre))

    df_precos_1_semestre["Valor de Venda"] = (
        df_precos_1_semestre["Valor de Venda"]
        .str.replace(",", ".")
        .astype(float)
    )

    df_filtrado = df_precos_1_semestre.copy(deep=True)

    df_resultado_total = (
        df_filtrado
        .groupby(
            ["Estado - Sigla", "Municipio"],
            as_index=False
        )
        .agg(
            media_preco=("Valor de Venda", "mean"),
            maior_preco=("Valor de Venda", "max"),
            menor_preco=("Valor de Venda", "min")
        )
    )

    # maior preço
    df_maiores_precos = (
        df_resultado_total
        .sort_values(
            by="maior_preco",
            ascending=False
        )
    )

    # maior média
    df_media_precos = (
        df_resultado_total
        .sort_values(
            by="media_preco",
            ascending=False
        )
    )

    # menor preço
    df_menores_precos = (
        df_resultado_total
        .sort_values(
            by="menor_preco",
            ascending=True
        )
    )

    # primeiro de cada um
    df_primeiro_maior_preco = df_maiores_precos.head(1)

    df_primeiro_media_preco = df_media_precos.head(1)

    df_primeiro_menor_preco = df_menores_precos.head(1)

    print("\nMAIOR PREÇO:")
    display(df_primeiro_maior_preco)

    print("\nMAIOR MÉDIA:")
    display(df_primeiro_media_preco)

    print("\nMENOR PREÇO:")
    display(df_primeiro_menor_preco)